apiVersion: apps/v1
kind: Deployment
metadata:
  name: am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: am
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: am-env-secrets
        - configMapRef:
            name: platform-config
        - secretRef:
            name: amster-env-secrets # Needed for public amster key
        - secretRef:
            name: ds-env-secrets # passwords for cts, userstore, etc
        image: am
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /am/isAlive.jsp
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        name: openam
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /am/isAlive.jsp
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 1000Mi
            cpu: 250m
        volumeMounts:
        - name: truststore
          mountPath: /var/run/secrets/truststore
        - name: am-secrets
          mountPath: /var/run/secrets/am
        - name: amster-keys
          mountPath: /var/run/secrets/amster
      terminationGracePeriodSeconds: 10
      volumes:
      - name: am-secrets
        projected:
          sources:
          - secret:
             name: am-passwords
          - secret:
              name: am-keystore
      - name: ds
      - name: amster-keys
        secret:
          secretName: amster
      - name: truststore
        secret:
          secretName: truststore