kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: am
  # Prometheus selector
  component: am
  tier: middle
  vendor: forgerock
# - ingress.yaml
resources:
- deployment.yaml
- service.yaml
