apiVersion: batch/v1
kind: Job
metadata:
  name: forgeops-secrets
spec:
  template:
    metadata:
      labels:
        app: forgeops-secrets
    spec:
      serviceAccountName: forgeops-secrets-serviceaccount
      restartPolicy: Never
      containers:
      - name: forgeops-secrets
        image: forgeops-secrets