kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: forgeops-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: forgeops-secrets-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: forgeops-secrets-role
  apiGroup: rbac.authorization.k8s.io