apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.additionalRulesLabels }}
{{ toYaml .Values.additionalRulesLabels | indent 4 }}
    {{- end }}
  name: {{ .Release.Name }}-fr.rules
spec:
{{- if .Values.prometheusRules }}
  groups:
{{ toYaml .Values.prometheusRules | indent 4 }}
{{ else }}
{{ include "fr.rules.yaml.tpl" . | indent 2 }}
{{ end }}