# Test skaffold - so you can test this service standalone
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: forgeops-secrets
    context: .
deploy:
  kustomize:
      path: ../../kustomize/base/forgeops-secrets