# Cloud build that is triggered from a git commit.
steps:
# Clean up any older deploys.
- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  args: ['--default-repo', 'gcr.io/$PROJECT_ID', '-p', 'smoke', 'delete']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args: ['./bin/clean.sh', 'smoke']
- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: 'bash'
  args: ['./bin/config.sh', 'init', '-p', 'cdk', '-v', '7.0']
- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  args: ['--default-repo', 'gcr.io/$PROJECT_ID/smoke', '-p', 'smoke', '--status-check=false', 'run']
options:
  env: ['CLOUDSDK_COMPUTE_ZONE=us-east1-c', 'CLOUDSDK_CONTAINER_CLUSTER=eng-shared']
