# skaffold -f skaffold-6.5.yaml dev
# For creating your own custom skaffold profiles we recommend making a copy of this
# file to skaffold-dev.yaml (which is in .gitignore).
# You can "mix and match" diferent services together by creating skaffold profiles
# and by creating a new kustomize profile in kustomize/6.5/env

# The default below for skaffold dev is to deploy all services in one shot:
apiVersion: skaffold/v1
kind: Config
build: &default-build
  # local:
  #   push: false
  #   useDockerCLI: false
  artifacts:
  - image: am
    context: docker/6.5/am
  - image: amster
    context: docker/6.5/amster
  - image: idm
    context: docker/6.5/idm
  - image: ds-cts
    context: docker/6.5/ds/cts
    docker:
      noCache: true
  - image: ds-idrepo
    context: docker/6.5/ds/idrepo
    docker:
      noCache: true
  - image: ig
    context: docker/6.5/ig
  - image: forgeops-secrets
    context: docker/forgeops-secrets
  tagPolicy:
    sha256: {}
deploy:
  statusCheckDeadlineSeconds: 600
  kustomize:
    path: ./kustomize/overlay/6.5/all
# Additional profiles
profiles:
# build base images. Example:
# skaffold -f skaffold-6.5.yaml --default-repo gcr.io/engineering-devops -p base build
- name: base
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:6.5"
    artifacts:
    - image: am-base
      context: docker/6.5/am-base
    - image: amster-base
      context: docker/6.5/amster-base
    - image: ig-base
      context: docker/6.5/ig-base
    - image: idm-base
      context: docker/6.5/idm-base
    - image: ds-base
      context: docker/6.5/ds-base
- name: large
  build: *default-build
  deploy:
    kustomize:
        path: ./kustomize/overlay/6.5/large
- name: medium
  build: *default-build
  deploy:
    kustomize:
        path: ./kustomize/overlay/6.5/medium
- name: small
  build: *default-build
  deploy:
    kustomize:
        path: ./kustomize/overlay/6.5/small

# 24/7 Demo environment
- name: nightly
  build:
    artifacts:
    - image: am
      context: docker/6.5/am
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
#       cache: {} DO NOT specify cache object.
    - image: amster
      context: docker/6.5/amster
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
    - image: idm
      context: docker/6.5/idm
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
    - image: ds-cts
      context: docker/6.5/ds/cts
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
    - image: ds-idrepo
      context: docker/6.5/ds/idrepo
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
    - image: forgeops-secrets
      context: docker/forgeops-secrets
      kaniko:
        image: gcr.io/kaniko-project/executor:8d9e6b8ea54274f73517f11c113c13cd03d26349
    cluster:
      namespace: nightly
      pullSecretName: kaniko-secret
      #dockerConfig:
        #path: ./config.json
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/6.5/nightly
- name: oauth2
  build: *default-build
  deploy:
    kustomize:
        path: ./kustomize/overlay/6.5/oauth2

# Sample profile to demonstrate connecting to an external DS instance instead of ds-idrepo in the cluster
# See the README.md in kustomize/6.5/env/external-ds/
- name: external-ds
  build: *default-build
  deploy:
    kustomize:
        path: ./kustomize/overlay/6.5/external-ds
