# For creating your own custom skaffold profiles we recommend making a copy of this
# file to skaffold-dev.yaml (which is in .gitignore).
# You can "mix and match" diferent services together by creating skaffold profiles
# and by creating a new kustomize profile in kustomize/overlay/
# The default below for skaffold dev is to deploy all services in one shot:
# Note: Upgrade to skaffold/v2alpha3 for skaffold 1.4
apiVersion: skaffold/v1
kind: Config

## Common YAML anchors
## The yaml anchors are used to make it easier to compose skaffold profiles.
## You should not need to edit this section
.YamlAnchors:
  kaniko:
    kaniko-ops: &kaniko-opts
      # Disable build cache for now. This is causing intermittent problems
      # cache: {}
      image: gcr.io/kaniko-project/executor:v0.20.0
      # The flags is deprecated - but without it we are seeing Kaniko bugs.
      # CLOUD-1955
      flags:
        - '--single-snapshot'
      # This is the recommended way of passing the single-snapshot arg - but we see issues.
      # buildArgs:
        # single-snapshot: "true"
    cluster: &kaniko-cluster
      namespace: kaniko
      pullSecretName: kaniko-secret

  artifactDefinitions:
    - &AM
      image: am
      context: docker/7.0/am
    - &AM_KANIKO
      <<: *AM
      kaniko: *kaniko-opts
    - &AMSTER
      image: amster
      context: docker/7.0/amster
    - &AMSTER_KANIKO
      <<: *AMSTER
      kaniko: *kaniko-opts
    - &IDM
      image: idm
      context: docker/7.0/idm
    - &IDM_KANIKO
      <<: *IDM
      kaniko: *kaniko-opts
    - &DS-CTS_BASE
      image: ds-cts
      context: docker/7.0/ds
    - &DS-CTS
      <<: *DS-CTS_BASE
      docker:
        dockerfile: cts/Dockerfile
    - &DS-CTS_KANIKO
      <<: *DS-CTS_BASE
      kaniko:
        <<: *kaniko-opts
        dockerfile: cts/Dockerfile

    - &DS-IDREPO_BASE
      image: ds-idrepo
      context: docker/7.0/ds/
    - &DS-IDREPO
      <<: *DS-IDREPO_BASE
      docker:
        dockerfile: idrepo/Dockerfile
    - &DS-IDREPO_KANIKO
      <<: *DS-IDREPO_BASE
      kaniko:
        <<: *kaniko-opts
        dockerfile: idrepo/Dockerfile

    - &FORGEOPS-SECRETS
      image: forgeops-secrets
      context: docker/forgeops-secrets
    - &FORGEOPS-SECRETS_KANIKO
      <<: *FORGEOPS-SECRETS
      kaniko: *kaniko-opts

    - &LDIF-IMPORTER
      image: ldif-importer
      context: docker/7.0/ldif-importer

    - &LDIF-IMPORTER_KANIKO
      image: ldif-importer
      context: docker/7.0/ldif-importer
      kaniko: *kaniko-opts

    - &IG
      image: ig
      context: docker/7.0/ig

  commonArtifactSets:
    default-artifacts: &default-artifacts
    - *AM
    - *AMSTER
    - *IDM
    - *DS-CTS
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    - *IG
    - *LDIF-IMPORTER
    kaniko-artifacts: &kaniko-artifacts
    - *AM_KANIKO
    - *AMSTER_KANIKO
    - *IDM_KANIKO
    - *DS-CTS_KANIKO
    - *DS-IDREPO_KANIKO
    - *FORGEOPS-SECRETS_KANIKO
    - *LDIF-IMPORTER_KANIKO

## End YAML Anchors

#---------------------
# Skaffold profiles
#---------------------

# Default profile
build: &default-build
  artifacts: *default-artifacts
  tagPolicy:
    sha256: {}
deploy: &default-deploy
  statusCheckDeadlineSeconds: 600
  kustomize:
    path: ./kustomize/overlay/7.0/all


# default.iam.forgeops.com
profiles:
- name: forgeops
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/forgeops

# 24/7 Demo environment
- name: nightly
  build: &kaniko-build
    artifacts: *kaniko-artifacts
    cluster: *kaniko-cluster
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/nightly

# Smoke tests
- name: smoke
  build:
    artifacts: *kaniko-artifacts
    cluster: *kaniko-cluster
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/smoke

# Default with Kaniko
- name: default-kaniko
  build: *kaniko-build
  deploy: *default-deploy

# kdev - development build for the toolbox image, using the generated kustomize
- name: kdev
  build: *kaniko-build
  deploy:
    kustomize:
        path: ./dev

# skaffold dev will not work with this, due to a new kustomize api thats being used for patching all objects
# ensure psp controller is enabled e.g. gcloud beta container clusters update cloud-1472 --enable-pod-security-policy --zone us-east4
- name: security
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/security

# CDM s/m/l profiles. (For cdm-mini, use default profile.)
- name: small
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/small
- name: medium
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/medium
- name: large
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/large

# Platform deployment sample used for PIT and PERF tests
- name: platform-deployment
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/lodestar

# Platform deployment without default UI projects. UI to be installed separately, for development
- name: no-ui
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/noui

# Sample profiles to launch / test just a specific product
- name: ig-only
  build:
    artifacts:
    - *IG
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/ig-only

- name: am-only
  build:
    artifacts:
    - *AM
    - *AMSTER
    - *DS-CTS
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    - *LDIF-IMPORTER
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/am-only

- name: idm-only
  build:
    artifacts:
    - *IDM
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/idm-only

- name: ds-only
  build:
    artifacts:
    - *DS-CTS
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/ds-only

# Deploy only ds and secrets.
- name: persistence
  build:
    artifacts:
    - *DS-CTS
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    - *LDIF-IMPORTER
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/persistence

# deploy only AM/IDM - for iterative testing
- name: am-idm-only
  build:
    artifacts:
    - *AM
    - *IDM
    - *AMSTER
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/am-idm-only

- name: amster-export
  build:
    artifacts:
    - *AMSTER
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/amster-export
