# Create a cluste wide issuer that uses cert managers built in CA issuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: certmanager-ca-secret