steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/engineering-devops/gcr-pruner:latest', '-f', 'etc/gke/pruner/Dockerfile', 'etc/gke/pruner' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/engineering-devops/gcr-pruner:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '--service-account=gcr-pruner@engineering-devops.iam.gserviceaccount.com'
    - '--image=gcr.io/engineering-devops/gcr-pruner:latest'
    - '--timeout=600'
    - '--platform=managed'
    - '--region=us-east1'
    - 'gcr-pruner'
images:
- 'gcr.io/engineering-devops/gcr-pruner:latest'


