# A sample K8S job to run the ds benchmark
apiVersion: batch/v1
kind: Job
metadata:
  name: ds-bench
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: create-users
        image: dsutil
        # ds-bench args:  <test to run - all> <duration in sec> <hostname> <users>
        args: ["-c", "/opt/opendj/bin/ds-bench.sh all 60 ds-idrepo-0.ds-idrepo 1000"]
        # Set the uid=admin password here.
        env:
        - name: ADMIN_PW
          value: "password"

