apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsutil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsutil
  template:
    metadata:
      labels:
        app: dsutil
    spec:
      containers:
      - name: dsutil
        image: dsutil
      terminationGracePeriodSeconds: 10