apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-users
spec:
  params:
  - name: users
    type: string
    description: number of users to create

  - name: namespace
    type: string
    description: target namespace

  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: "slack-webhook-$(params.namespace)"
          key: SLACK_FAILED_WEBHOOK_URL
  steps:
  - name: create-users
    image: gcr.io/cloud-builders/kubectl
    script: |
      #!/usr/bin/env bash
      {
        #set ADMIN_PASSWORD and run make-users.sh

        ADMIN_PASSWORD=$(kubectl -n $(params.namespace) get secret ds-passwords -o jsonpath="{.data.dirmanager\.pw}" | base64 --decode)
        kubectl -n $(params.namespace) exec ds-idrepo-0 -- bash -c "ADMIN_PASSWORD=$ADMIN_PASSWORD make-users.sh $(inputs.params.users)"
      } || {
        curl -X POST -H 'Content-type: application/json' --data '{"text":"$(params.namespace): Failed to create users. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
        exit 1
      }

