resources:
- ../all
- ../../../base/ig

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    AM_STORES_USER_SERVERS: "ds-idrepo-0.ds-idrepo:1389,ds-idrepo-1.ds-idrepo:1389"
    AM_STORES_CTS_SERVERS: "ds-cts-0.ds-cts:1389,ds-cts-1.ds-cts:1389"

- |-
  #Patch AM
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: am
  spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: openam
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 11
                memory: 8Gi
              limits:
                cpu: 12
                memory: 11Gi

- |-
  #Patch DS CTS
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-cts
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: ds
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 2
                memory: 8Gi
              limits:
                cpu: 8
                memory: 11Gi
        initContainers:
          - name: initialize
            imagePullPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 850Gi
        storageClassName: fast

- |-
  #Patch DS IDREPO
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-idrepo
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: ds
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 2
                memory: 8Gi
              limits:
                cpu: 8
                memory: 11Gi
        initContainers:
          - name: initialize
            imagePullPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 850Gi
        storageClassName: fast

- |-
  #Patch IDM
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: idm
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: openidm
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 8
              memory: 4Gi
            limits:
              cpu: 10
              memory: 6Gi
          env:
            - name: JAVA_OPTS
              value: -server -XX:MaxRAMPercentage=75 -Xlog:gc:/tmp/gc.log

- |-
  #Patch IG
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ig
  spec:
    template:
      spec:
        containers:
          - name: ig
            imagePullPolicy: Always
