# Sample demonstrating connecting to an external ds instance
# In production it is recommended to use TLS
apiVersion: v1
kind: Service
metadata:
  name: ds-idrepo
spec:
  ports:
    - protocol: TCP
      port: 1389
      targetPort: 1380
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ds-idrepo
subsets:
  - addresses:
      - ip: 35.230.30.59
    ports:
      - port: 1389