# This deploys to default.iam.example.com. It uses the ca-issuer
# for self signed SSL certs. It is suitable for local minikube development
namespace: default
resources:
- ../../../base/6.5/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/6.5/ds/cts
- ../../../base/am
- ../../../base/amster
- ../../../base/6.5/ingress
- external-ds.yaml
# In this example we use an external ds instance
# - ../../../base/6.5/ds/idrepo
# - ../../../base/postgres
# - ../../../base/idm


