---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-tag-listener
spec:
  serviceAccountName: tekton-trigger
  triggers:
    - name: github-tag-trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secret
            eventTypes:
              - create
        - cel:
            filter: "body.ref_type == 'tag'"
      bindings:
        - name: tag-release-binding
      template:
        name: tag-release-template
