apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgerock-default-rolebinding
  namespace: $(NAMESPACE)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgerock-default-role
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgerock-webserver-rolebinding
  namespace: $(NAMESPACE)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgerock-webserver-role
subjects:
- kind: ServiceAccount
  name: forgerock-webserver
