apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgerock-default-role
  namespace: $(NAMESPACE)
rules:
- apiGroups:
  - extensions
  resourceNames:
  - forgerock-default-policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgerock-webserver-role
  namespace: $(NAMESPACE)
rules:
- apiGroups:
  - extensions
  resourceNames:
  - forgerock-webserver-policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
