kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: postgres-idm
resources:
- statefulset.yaml
- service.yaml
configMapGenerator:
- files:
  - sql/01_openidm.sql
  - sql/02_default_schema_optimization.sql
  - sql/03_audit.sql
  - sql/activiti.postgres.create.engine.sql
  - sql/activiti.postgres.create.history.sql
  - sql/activiti.postgres.create.identity.sql
  - sql/sample-explicit-managed-user.sql
  name: openidm-sql
