apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-idm
spec:
  selector:
    matchLabels:
      app: postgres-idm
  serviceName: postgresql
  replicas: 1
  template:
    spec:
      initContainers:
      # This cleans up the lost+found at the root of pgdata. Postgres will not start if this directory is present.
      - name: init
        image: "busybox:1.25.0"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgres-idm
          mountPath: /var/lib/postgresql/data/pgdata
        command:  ["rm", "-fr", "/var/lib/postgresql/data/pgdata/lost+found"]
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: openidm
        - name: PGUSER
          value: openidm
        - name: POSTGRES_DB
          value: ""
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        # Adding the default values here just to provide a place to tune further
        args: ['-c','shared_buffers=128MB','-c','max_connections=100']
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 30
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: postgres-idm
          mountPath: /var/lib/postgresql/data/pgdata
        - name: sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: sql
        configMap:
          name: openidm-sql
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: postgres-idm
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
          
