apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: utils-pipeline
spec:
  resources:
    - name: forgeops
      type: git
  tasks:
    - name: sample-pr-step
      taskRef:
        name: sample-pr-task
      resources:
        inputs:
        - name: forgeops
          resource: forgeops
      params:
      - name: profile
        value: utils
        
