apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: utils
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: utils
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: utils-run-
    spec:
      timeout: 30m
      serviceAccountName: tekton-worker
      pipelineRef:
        name: utils-pipeline
      resources:
      - name: forgeops
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.gitrevision)
          - name: url
            value: $(params.gitrepositoryurl)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: utils-listener
spec:
  serviceAccountName: tekton-trigger
  triggers:
  - name: pr-trigger
    interceptors:
    - cel:
        filter: "string(decodeb64(split(header['Authorization'][0], 'Basic ')[1])).compareSecret('authorization', 'bitbucket-pr-secret')"
        overlays:
        - key: head_commit.id
          expression: "body.sourceHash" 
        - key: repository.url
          expression: "body.sourceCloneHTTP" 
    bindings:
    - name: utils
    template:
      name: utils          

