encryptionsalt: v1:OGMSatR2kak=:v1:wXpXDZgHmyHrdIR1:f8WLl5uQaTIyGmX9OVsR+LZMbrHyaA==
config:
  aws:region: us-east-1
  aws-infra:bastionEnable: "false"
  aws-infra:bastionAmi: ami-0e70db31f7e942241
  aws-infra:bastionInstanceType: t2.micro
  aws-infra:bucketName: eks-cdm
  aws-infra:highAvailability: "true"
  aws-infra:numOfAzs: "3"
  aws-infra:vpcCIDR: 192.168.0.0/16
  aws-infra:pubKey:
    secure: v1:z//BZlrJFEZIRtml:cEEHG5XJ6/VYJ4MbPpfYKyQiGVl8KvkwtiIvqLpLNLTygne/yOroA95XBDopdOrYiKB4QVcw/jFBl0xm9vevpTuKcX8Dp8smqOuW4VmucpBjMh2xtit3tpWIdm6BCH6HpuQHZ71oubli9x3tTzaB4JKjEYOsukhEfDJlPwc79S4yLxYjTydHmMD98phOx+YcSUls6xOpN2tsft/coXxV6ZQgB+nHA0g9aTfZWh3yYTI9S1QAgdbls6ar8n2ajkhDtTiYQMEExgaJJpYKFgoxlzKx8F2wVc/1mgTn66f0wQ2I6/5IQ0vlFA8u9+stORFPDTMRFebW7I8P3R91cXAGqzExL05iMdi31GhxmpUw3miS68uT9IVHA/zKw93mrpI07yEOJvwtzseE2a2B9Vgey5KQkitbIVu7ZfGvNSihFJtq4dMOIVe+M9q6yIOU7UvHH184IgDm/gaeXQEIZKUV5h7JqZcJc8AhkAJkn/u0PZx8j1odJJrP4eWdjbwNkgBzBivMe5OBd+u4Ieu15hxEBQS0qqLQKgsGgih0lU6IpR2d3YzlTKjV2AaGlVcI7aq6Dtvi811s+UCBIgfPWOZnmWSgT8R9+i61ErcSlvSD0nPxSMpFkmSWdKKVDQxdx0pibBj9Lh4pPBLoxN4ig44TngzhZxWPBb++KBOzN7FOioTNgLEsMQRf2DFWeTzp8di/jfbjAhlKs65U34tRSoNR9f7xV6FHkyePfGlVXTZor4+uKOgK6pwODa7u422/MTMho3VgJAB4CMjr3p73AfJC14HAQ1jWSP+ICIZ5OrRHUqKpkIN6bXavzTIppJdXCGWQZRIXrkbajMeaDyfXQdv/XblihCiQx3eqNRk4ZDPLbUFfH/+YM2j+cCRV2pxV4OW0u8Cl0Y+q1bg6/044BJQ3G04cskyL1NuLie0BNm5aFJoORVyzoZPqBDxBhGqu78CNm8TeEIVx/t5CE+i/2sqv8NgceQPHzVNPJuDG7/Bv/MrIJHb5LnjGNcFfT/jrSSGylG411SE=
