apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nightly-pipeline
spec:
  resources:
    - name: forgeops
      type: git
  params:
    - name: namespace
      type: string
      description: Target namespace of this pipeline
      default: nightly
    - name: skaffold-profile
      type: string
      description: Skaffold profile to deploy
      default: nightly
  tasks:
    - name: deploy-images-step
      taskRef:
        name: deploy-images
      resources:
        inputs:
        - name: forgeops
          resource: forgeops
      params:
      - name: profile
        value: "$(params.skaffold-profile)"
      - name: namespace
        value: "$(params.namespace)"
      - name: docker-repo
        value: gcr.io/engineering-devops/nightly

    - name: wait-platform-up-step
      taskRef:
        name: wait-platform-up
      runAfter:
      - deploy-images-step
      params:
      - name: namespace
        value: "$(params.namespace)"

    - name: scale-am-deployment-step
      runAfter:
      - wait-platform-up-step
      taskRef:
        name: scale-am-deployment
      params:
      - name: replicas
        value: "1"
      - name: namespace
        value: "$(params.namespace)"

    # The smoke test creates 5 users as part of the test
    - name: run-tests
      taskRef:
        name: smoke-test
      runAfter:
      - scale-am-deployment-step
      resources:
        inputs:
        - name: forgeops
          resource: forgeops
      params:
      - name: namespace
        value: "$(params.namespace)"


    - name: notify-step
      runAfter:
      - scale-am-deployment-step
      taskRef:
        name: notify
      resources:
        inputs:
        - name: forgeops
          resource: forgeops
      params:
      - name: namespace
        value: "$(params.namespace)"
