# Run the utility ds image
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: dsutil
    context: .
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
profiles:
- name: ds-bench
  deploy:
    kubectl:
      manifests:
      - k8s/bench-job.yaml