# Run the gatling performance tests
apiVersion: batch/v1
kind: Job
metadata:
  name: perf-test
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        name: perf-test
    spec:
      containers:
      - image: gatling
        name: perf-test
        resources:
          limits:
            memory: 3000Mi
          requests:
            cpu: 500m
            memory: 2500Mi
        envFrom:
        - configMapRef:
            name: perf-test-config
        volumeMounts:
        - name: gcs-key
          mountPath: /var/run/secrets
      restartPolicy: Never
      volumes:
      - name: gcs-key
        secret:
          secretName: gcs-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-test-config
data:
  # Customize as required
  GOOGLE_APPLICATION_CREDENTIALS: "/var/run/secrets/key.json"
  DURATION: "60"
  CONCURRENCY: "50"
  TARGET_HOST: "smoke.iam.forgeops.com"