# Override values for Prometheus.
# Possible values to override can be found here:
# https://github.com/coreos/prometheus-operator/tree/master/helm/prometheus-operator

## Prometheus-config-reloader image to use for config and rule reloading
##
prometheusConfigReloaderImage:
  repository: quay.io/coreos/prometheus-config-reloader
  tag: v0.32.0
  
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.32.0

alertmanagerSpec:
  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.19.0

  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: fast
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi

grafana:
  storageSpec:
    class: fast
    accessMode: "ReadWriteOnce"
    resources:
     requests:
       storage: 20Gi  

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  
  adminPassword: password

prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.12.0

prometheusSpec:
  retention: 30d

  ruleSelector: 
    matchLabels:
    role: alert-rules
    #   prometheus: prometheus-operator

  serviceMonitorSelector:
    matchLabels:
      prometheus: prometheus-operator

  storageSpec:
    volumeClaimTemplate:
      metadata:
        name: prometheus-metrics
        annotations:
          "helm.sh/resource-policy": keep
      spec:
        storageClassName: fast
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi