namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../base/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/7.0/ds/cts
- ../../../base/7.0/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/7.0/ingress
- ../../../base/ldif-importer
