apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  selector:
    matchLabels:
      app: ds
  serviceName: ds
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                      - directory
                topologyKey: kubernetes.io/hostname
              weight: 100
      tolerations:
      - key: "WorkerDedicatedDS"
        operator: "Exists"
      initContainers:
        - name: restore
          image: ds
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: data
            mountPath: /opt/opendj/data
          - name: backup
            mountPath: /opt/opendj/bak
          - name: secrets
            mountPath: /var/run/secrets/opendj
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FQDN_DS0
            value: localhost
          - name: BACKUP_DIRECTORY
            value: /opt/opendj/bak

          args: [ "restore" ]
          envFrom:
            - configMapRef:
                name: ds
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
      containers:
        - name: ds
          image: ds
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FQDN_DS0
              value: localhost
            - name: BACKUP_DIRECTORY
              value: /opt/opendj/bak
          envFrom:
            - configMapRef:
                name: ds
          # See https://bugster.forgerock.org/jira/browse/CLOUD-1877
          # Live / Ready probes complicate DS operations. Pod restart rarely solves DB issues.
          # livenessProbe:
          #   initialDelaySeconds: 60
          #   periodSeconds: 120
          #   httpGet:
          #     path: /alive
          #     port: http
          ports:
            - name: ldap
              containerPort: 1389
            - name: ldaps
              containerPort: 1636
            - name: admin
              containerPort: 4444
            - name: replication
              containerPort: 8989
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /opt/opendj/data
            name: data
          - mountPath: /opt/opendj/secrets
            name: secrets
          - mountPath: /var/run/secrets/opendj
            name: secrets
          - name: backup
            mountPath: /opt/opendj/bak
      securityContext:
        fsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secrets
          secret:
            secretName: ds
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: backup
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
