apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
- ../all
- ../../../base/security

images:
- name: forgeops-secrets
  newName: gcr.io/engineering-devops/forgeops-secrets
  newTag: latest

patches:
- patch: &securityContextPatch |-
    kind: doesnt-matter
    metadata:
      name: doesnt-matter
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 11111
            fsGroup: 11111
  target:
    kind: Deployment
    labelSelector: app notin (end-user-ui)
- patch: *securityContextPatch
  target:
    kind: StatefulSet
    labelSelector: app notin (end-user-ui)
- patch: *securityContextPatch
  target:
    kind: Job
    labelSelector: app notin (end-user-ui)
# add default-policy to forgeops-secrets-role
- patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - extensions
        resourceNames:
        - forgerock-default-policy
        resources:
        - podsecuritypolicies
        verbs:
        - use
  target:
    name: forgeops-secrets-role
# patch end-user-ui for webserver to run as root
- patch: |-
    kind: doesnt-matter
    metadata:
      name: doesnt-matter
    spec:
      template:
        spec:
          serviceAccount: forgerock-webserver
          securityContext:
            runAsUser: 101
            fsGroup: 101
  target:
    kind: Deployment
    labelSelector: app in (end-user-ui)
