namespace: default
resources:
- ../../../base/6.5/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/postgres
- ../../../base/6.5/ds/cts
- ../../../base/6.5/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/6.5/ingress
