namespace: nightly
resources:
- ../all

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    DOMAIN: "forgeops.com"
    FQDN: "nightly.iam.forgeops.com"
    CERT_ISSUER: letsencrypt-prod



